name: abyssinia_shopping
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.4+1
  firebase_database: ^4.4.0
  flutter_swiper: ^1.1.2
  flutter_staggered_grid_view: ^0.3.0
  rubber: ^0.3.2
  pin_code_text_field: ^1.6.0
  country_code_picker: ^1.1.5
  http: ^0.12.2
  flutter_rating_bar: ^1.3.0+1
  intl: any
  numberpicker: ^1.0.0
  flare_splash_screen: ^2.1.2
  flutter_svg: ^0.18.0
  cached_network_image: ^2.4.1
  font_awesome_flutter: ^8.10.1
  lazy_load_scrollview: 1.1.0
  fluttertoast: ^7.1.6
  permission_handler: ^5.0.1+1
  google_maps_flutter: ^1.0.6
  geolocator: ^6.1.13
  geocoder: ^0.2.1
  location: ^3.2.1
  url_launcher: ^5.7.10
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

